# Generated by Django 5.0.2 on 2024-02-29 11:51

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='file',
            field=models.FileField(upload_to='', validators=[products.models.validate_file_extension]),
        ),
    ]
