# Generated by Django 5.0.2 on 2024-02-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_session_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/photos/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(upload_to='media/photos/'),
        ),
    ]
