# Generated by Django 5.0.2 on 2024-03-05 13:44

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Produkt'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'Sesja'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/photos/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='session',
            name='file',
            field=models.FileField(upload_to='', validators=[products.models.validate_file_extension], verbose_name='Plik tekstowy'),
        ),
        migrations.AlterField(
            model_name='session',
            name='film',
            field=models.URLField(verbose_name='Link do filmu'),
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(upload_to='media/photos/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='session',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produkt'),
        ),
    ]
