# Generated by Django 5.0.2 on 2024-03-30 11:41

import ckeditor.fields
import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_session_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='session',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[products.models.validate_file_extension], verbose_name='Plik tekstowy'),
        ),
        migrations.AlterField(
            model_name='session',
            name='film',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Film'),
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/', verbose_name='Zdjęcie'),
        ),
    ]
